
// src/lib/legal-data.ts

export const ipcData = [
    { section: "Section 120B", description: "Punishment of criminal conspiracy." },
    { section: "Section 121", description: "Waging, or attempting to wage war, or abetting waging of war, against the Government of India." },
    { section: "Section 124A", description: "Sedition." },
    { section: "Section 141", description: "Unlawful assembly." },
    { section: "Section 146", description: "Rioting." },
    { section: "Section 153A", description: "Promoting enmity between different groups on grounds of religion, race, place of birth, residence, language, etc., and doing acts prejudicial to maintenance of harmony." },
    { section: "Section 295A", description: "Deliberate and malicious acts, intended to outrage religious feelings of any class by insulting its religion or religious beliefs." },
    { section: "Section 299", description: "Culpable homicide." },
    { section: "Section 300", description: "Murder. Culpable homicide is murder, if the act by which the death is caused is done with the intention of causing death..." },
    { section: "Section 302", description: "Punishment for murder. Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine." },
    { section: "Section 304", description: "Punishment for culpable homicide not amounting to murder." },
    { section: "Section 304A", description: "Causing death by negligence." },
    { section: "Section 304B", description: "Dowry death." },
    { section: "Section 307", description: "Attempt to murder. Whoever does any act with such intention or knowledge, and under such circumstances that, if he by that act caused death, he would be guilty of murder, shall be punished..." },
    { section: "Section 308", description: "Attempt to commit culpable homicide." },
    { section: "Section 354", description: "Assault or criminal force to woman with intent to outrage her modesty." },
    { section: "Section 354D", description: "Stalking." },
    { section: "Section 375", description: "Rape. A man is said to commit rape who penetrates his penis, to any extent, into the vagina, mouth, urethra or anus of a woman or makes her to do so with him or any other person..." },
    { section: "Section 376", description: "Punishment for rape." },
    { section: "Section 377", description: "Unnatural offences." },
    { section: "Section 378", description: "Theft. Whoever, intending to take dishonestly any moveable property out of the possession of any person without that person’s consent, moves that property in order to such taking, is said to commit theft." },
    { section: "Section 379", description: "Punishment for theft." },
    { section: "Section 383", description: "Extortion." },
    { section: "Section 390", description: "Robbery." },
    { section: "Section 391", description: "Dacoity." },
    { section: "Section 395", description: "Punishment for dacoity." },
    { section: "Section 405", description: "Criminal breach of trust." },
    { section: "Section 415", description: "Cheating." },
    { section: "Section 420", description: "Cheating and dishonestly inducing delivery of property. Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person..." },
    { section: "Section 441", description: "Criminal trespass." },
    { section: "Section 463", description: "Forgery." },
    { section: "Section 498A", description: "Husband or relative of husband of a woman subjecting her to cruelty." },
    { section: "Section 499", description: "Defamation. Whoever, by words either spoken or intended to be read, or by signs or by visible representations, makes or publishes any imputation concerning any person intending to harm..." },
    { section: "Section 503", description: "Criminal intimidation. Whoever threatens another with any injury to his person, reputation or property..." },
    { section: "Section 506", description: "Punishment for criminal intimidation." },
    { section: "Section 509", description: "Word, gesture or act intended to insult the modesty of a woman." },
];

export const constitutionArticles = [
  { article: "Article 1", description: "Name and territory of the Union." },
  { article: "Article 2", description: "Admission or establishment of new States." },
  { article: "Article 3", description: "Formation of new States and alteration of areas, boundaries or names of existing States." },
  { article: "Article 14", description: "Equality before law. The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India." },
  { article: "Article 15", description: "Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth." },
  { article: "Article 16", description: "Equality of opportunity in matters of public employment." },
  { article: "Article 17", description: "Abolition of Untouchability." },
  { article: "Article 18", description: "Abolition of titles." },
  { article: "Article 19", description: "Protection of certain rights regarding freedom of speech, etc." },
  { article: "Article 20", description: "Protection in respect of conviction for offences." },
  { article: "Article 21", description: "Protection of life and personal liberty. No person shall be deprived of his life or personal liberty except according to procedure established by law." },
  { article: "Article 21A", description: "Right to education." },
  { article: "Article 22", description: "Protection against arrest and detention in certain cases." },
  { article: "Article 23", description: "Prohibition of traffic in human beings and forced labour." },
  { article: "Article 24", description: "Prohibition of employment of children in factories, etc." },
  { article: "Article 25", description: "Freedom of conscience and free profession, practice and propagation of religion." },
  { article: "Article 32", description: "Right to Constitutional Remedies. The right to move the Supreme Court for the enforcement of the rights conferred by this Part is guaranteed." },
  { article: "Article 51A", description: "Fundamental Duties. It shall be the duty of every citizen of India..." },
  { article: "Article 72", description: "Power of President to grant pardons, etc., and to suspend, remit or commute sentences in certain cases." },
  { article: "Article 76", description: "Attorney-General for India." },
  { article: "Article 123", description: "Power of President to promulgate Ordinances during recess of Parliament." },
  { article: "Article 143", description: "Power of President to consult Supreme Court." },
  { article: "Article 148", description: "Comptroller and Auditor-General of India." },
  { article: "Article 155", description: "Appointment of Governor." },
  { article: "Article 161", description: "Power of Governor to grant pardons, etc." },
  { article: "Article 280", description: "Finance Commission." },
  { article: "Article 324", description: "Election Commission." },
  { article: "Article 352", description: "Proclamation of Emergency (National Emergency)." },
  { article: "Article 356", description: "Provisions in case of failure of constitutional machinery in States (President's Rule)." },
  { article: "Article 360", description: "Provisions as to financial emergency." },
  { article: "Article 368", description: "Power of Parliament to amend the Constitution." },
  { article: "Article 370", description: "Temporary provisions with respect to the State of Jammu and Kashmir (repealed)." },
];

export const constitutionParts = [
    { part: "Part I", description: "The Union and its Territory (Articles 1-4)" },
    { part: "Part II", description: "Citizenship (Articles 5-11)" },
    { part: "Part III", description: "Fundamental Rights (Articles 12-35)" },
    { part: "Part IV", description: "Directive Principles of State Policy (Articles 36-51)" },
    { part: "Part IVA", description: "Fundamental Duties (Article 51A)" },
    { part: "Part V", description: "The Union (Articles 52-151)" },
    { part: "Part VI", description: "The States (Articles 152-237)" },
    { part: "Part VIII", description: "The Union Territories (Articles 239-242)" },
    { part: "Part IX", description: "The Panchayats (Articles 243-243O)" },
    { part: "Part IXA", description: "The Municipalities (Articles 243P-243ZG)" },
    { part: "Part X", description: "The Scheduled and Tribal Areas (Articles 244-244A)" },
    { part: "Part XI", description: "Relations between the Union and the States (Articles 245-263)" },
    { part: "Part XII", description: "Finance, Property, Contracts and Suits (Articles 264-300A)" },
    { part: "Part XIII", description: "Trade, Commerce and Intercourse within the Territory of India (Articles 301-307)" },
    { part: "Part XIV", description: "Services under the Union and the States (Articles 308-323)" },
    { part: "Part XIVA", description: "Tribunals (Articles 323A-323B)" },
    { part: "Part XV", description: "Elections (Articles 324-329A)" },
    { part: "Part XVI", description: "Special Provisions relating to Certain Classes (Articles 330-342)" },
    { part: "Part XVII", description: "Official Language (Articles 343-351)" },
    { part: "Part XVIII", description: "Emergency Provisions (Articles 352-360)" },
    { part: "Part XX", description: "Amendment of the Constitution (Article 368)" },
];

export const constitutionSchedules = [
    { schedule: "First Schedule", description: "Lists the states and territories of India." },
    { schedule: "Second Schedule", description: "Lists the salaries of public officials, judges, and the President." },
    { schedule: "Third Schedule", description: "Forms of Oaths and Affirmations." },
    { schedule: "Fourth Schedule", description: "Allocation of seats in the Rajya Sabha." },
    { schedule: "Fifth Schedule", description: "Provisions as to the Administration and Control of Scheduled Areas and Scheduled Tribes." },
    { schedule: "Sixth Schedule", description: "Provisions as to the Administration of Tribal Areas in the States of Assam, Meghalaya, Tripura and Mizoram." },
    { schedule: "Seventh Schedule", description: "Union List, State List, and Concurrent List." },
    { schedule: "Eighth Schedule", description: "List of recognized languages." },
    { schedule: "Ninth Schedule", description: "Validation of certain Acts and Regulations." },
    { schedule: "Tenth Schedule", description: "Provisions as to disqualification on ground of defection (Anti-Defection Law)." },
    { schedule: "Eleventh Schedule", description: "Powers, authority and responsibilities of Panchayats." },
    { schedule: "Twelfth Schedule", description: "Powers, authority and responsibilities of Municipalities." },
];

export const constitutionAmendments = [
    { amendment: "1st Amendment (1951)", description: "Added Ninth Schedule to protect land reform laws." },
    { amendment: "7th Amendment (1956)", description: "Reorganisation of states on linguistic lines." },
    { amendment: "24th Amendment (1971)", description: "Affirmed the power of Parliament to amend any part of the Constitution, including fundamental rights." },
    { amendment: "42nd Amendment (1976)", description: "The 'Mini-Constitution', added 'socialist' and 'secular' to the preamble, and laid down Fundamental Duties." },
    { amendment: "44th Amendment (1978)", description: "Removed the Right to Property from the list of Fundamental Rights." },
    { amendment: "52nd Amendment (1985)", description: "Added the Tenth Schedule (Anti-Defection Law)." },
    { amendment: "61st Amendment (1989)", description: "Lowered the voting age from 21 to 18." },
    { amendment: "73rd Amendment (1992)", description: "Granted constitutional status to Panchayati Raj institutions." },
    { amendment: "74th Amendment (1992)", description: "Granted constitutional status to Urban Local Bodies." },
    { amendment: "86th Amendment (2002)", description: "Made elementary education a fundamental right (Article 21A)." },
    { amendment: "97th Amendment (2011)", description: "Gave constitutional status and protection to co-operative societies." },
    { amendment: "101st Amendment (2016)", description: "Introduced the Goods and Services Tax (GST)." },
    { amendment: "102nd Amendment (2018)", description: "Gave constitutional status to the National Commission for Backward Classes." },
    { amendment: "103rd Amendment (2019)", description: "Provided 10% reservation for Economically Weaker Sections (EWS)." },
    { amendment: "104th Amendment (2020)", description: "Extended the reservation of seats for SCs and STs in the Lok Sabha and state assemblies." },
    { amendment: "105th Amendment (2021)", description: "Restored the power of state governments to identify and specify Socially and Educationally Backward Classes (SEBCs)." },
];

    